services:
  - type: web
    name: iamobil-gestor
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node server/index.cjs
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 10000
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: VITE_API_URL
        value: https://iamobil-cloud-1.onrender.com
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        value: 8766470825:AAEg6tUojiHHF6KCr4TPg-DQzxSMz72lvFU
        sync: false
